In [ ]:
import numpy as np
import random as rd
import gym

In [ ]:
env = gym.make("Taxi-v3")

In [ ]:
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [ ]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [ ]:
action_size

6

In [ ]:
qtable = np.zeros((state_size,action_size))
print(qtable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
total_episodes = 200000
test_episodes = 100
max_Steps = 100
learning_rate = 0.7
gamma = 0.85
epsilon = 1.0                
max_epsilon = 1.0            
min_epsilon = 0.01            
decay_rate = 0.01 

In [ ]:
for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    
    for step in range(max_Steps):
      
      exp_exp_tradeoff = rd.uniform(0,1)
        
      if exp_exp_tradeoff > epsilon:
        action = np.argmax(qtable[state,:])
        
      else:
        action = env.action_space.sample()
        
      new_state, reward, done, info = env.step(action)

      qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
                
      state = new_state
        
      if done == True: 
        break
    
    
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)

In [ ]:
env.reset()
rewards = []

for episode in range(test_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    #print("****************************************************")
    #print("EPISODE ", episode)

    for step in range(max_Steps):
        # UNCOMMENT IT IF YOU WANT TO SEE OUR AGENT PLAYING
        #env.render()
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        total_rewards += reward
        
        if done:
            rewards.append(total_rewards)
            #print ("Score", total_rewards)
            break
        state = new_state
env.close()
print ("Score over time: " +  str(sum(rewards)/test_episodes))

Score over time: 8.13


In [ ]:
env1 = gym.make("FrozenLake-v0")

In [ ]:
env1.render()


SFFF
FHFH
FFFH
HFFG
